# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build v2
      run: go build -v github.com/ilius/is/v2

    - name: Build v3
      run: go build -v github.com/ilius/is/v3

    - name: Test v2
      run: go test -v github.com/ilius/is/v2

    - name: Test v3
      run: go test -v github.com/ilius/is/v3